insert into f1_team (name, created_at, modified, points) values 
('Alfa Romeo', now(), now(), 0),
('AlphaTauri', now(), now(), 0),
('Alpine F1 Team', now(), now(), 0),
('Aston Martin', now(), now(), 0),
('Ferrari', now(), now(), 0),
('Haas F1 Team', now(), now(), 0),
('McLaren', now(), now(), 0),
('Mercedes', now(), now(), 0),
('Red Bull', now(), now(), 0),
('Williams', now(), now(), 0);

INSERT into f1_driver (number, "name", last_name ,points, team_id) values 
(55,'Carlos', 'Sainz', 0, (select id from f1_team where f1_team."name" = 'Ferrari') ),
(16,'Charles', 'Leclerc', 0, (select id from f1_team where f1_team."name" = 'Ferrari') ),
(10,'Pierre', 'Gasly', 0, (select id from f1_team where f1_team."name" = 'AlphaTauri') ),
(22,'Yuki', 'Tsunoda', 0, (select id from f1_team where f1_team."name" = 'AlphaTauri') ),
(44,'Lewis', 'Hamilton', 0, (select id from f1_team where f1_team."name" = 'Mercedes') ),
(63,'George', 'Russell', 0, (select id from f1_team where f1_team."name" = 'Mercedes') ),
(11,'Sergio', 'Pérez', 0, (select id from f1_team where f1_team."name" = 'Red Bull') ),
(33,'Max', 'Verstappen', 0, (select id from f1_team where f1_team."name" = 'Red Bull') ),
(5,'Sebastian', 'Vettel', 0, (select id from f1_team where f1_team."name" = 'Aston Martin') ),
(18,'Lance', 'Stroll', 0, (select id from f1_team where f1_team."name" = 'Aston Martin') ),
(27,'Nico', 'Hülkenberg', 0, (select id from f1_team where f1_team."name" = 'Aston Martin') ),
(4,'Lando', 'Norris', 0, (select id from f1_team where f1_team."name" = 'McLaren') ),
(3,'Daniel', 'Ricciardo', 0, (select id from f1_team where f1_team."name" = 'McLaren') ),
(20,'Kevin', 'Magnussen', 0, (select id from f1_team where f1_team."name" = 'Haas F1 Team') ),
(47,'Mick', 'Schumacher', 0, (select id from f1_team where f1_team."name" = 'Haas F1 Team') ),
(6,'Nicholas', 'Latifi', 0, (select id from f1_team where f1_team."name" = 'Williams') ),
(23,'Alexander', 'Albon', 0, (select id from f1_team where f1_team."name" = 'Williams') ),
(31,'Esteban', 'Ocon', 0, (select id from f1_team where f1_team."name" = 'Alpine F1 Team') ),
(14,'Fernando', 'Alonso', 0, (select id from f1_team where f1_team."name" = 'Alpine F1 Team') ),
(77,'Valtteri', 'Bottas', 0, (select id from f1_team where f1_team."name" = 'Alfa Romeo') ),
(24,'Guanyu', 'Zhou', 0, (select id from f1_team where f1_team."name" = 'Alfa Romeo') );

INSERT into f1_location("name", "city", "country") values
('Albert Park Grand Prix Circuit',	'Melbourne',	'Australia'),
('Circuit of the Americas',	'Austin',	'USA'),
('Bahrain International Circuit',	'Sakhir',	'Bahrain'),
('Baku City Circuit',	'Baku',	'Azerbaijan'),
('Circuit de Barcelona-Catalunya',	'Montmeló',	'Spain'),
('Hungaroring',	'Budapest',	'Hungary'),
('Autodromo Enzo e Dino Ferrari',	'Imola',	'Italy'),
('Autódromo José Carlos Pace',	'São Paulo',	'Brazil'),
('Jeddah Corniche Circuit	Jeddah',	'Saudi', 'Arabia'),
('Marina Bay Street Circuit',	'Marina Bay',	'Singapore'),
('Miami International Autodrome',	'Miami',	'United States'),
('Circuit de Monaco',	'Monte-Carlo',	'Monaco'),
('Autodromo Nazionale di Monza',	'Monza',	'Italy'),
('Red Bull Ring',	'Spielberg',	'Austria'),
('Circuit Paul Ricard',	'Le Castellet',	'France'),
('Autódromo Hermanos Rodríguez',	'Mexico City',	'Mexico'),
('Silverstone Circuit',	'Silverstone',	'UK'),
('Circuit de Spa-Francorchamps',	'Spa',	'Belgium'),
('Suzuka Circuit',	'Suzuka',	'Japan'),
('Circuit Gilles Villeneuve',	'Montreal',	'Canada'),
('Yas Marina Circuit',	'Abu Dhabi',	'UAE'),
('Circuit Park Zandvoort',	'Zandvoort',	'Netherlands');



INSERT into f1_race ("name",  "date", "location_id", completed ) values
('Bahrain Grand Prix',	'2022.03.20',	(select id from f1_location where f1_location."name" =	'Bahrain International Circuit'), FALSE),
('Saudi Arabian Grand Prix',	'2022.03.27',	(select id from f1_location where f1_location."name" =	'Jeddah Corniche Circuit'), FALSE),
('Australian Grand Prix',	'2022.04.10',	(select id from f1_location where f1_location."name" =	'Albert Park Grand Prix Circuit'), FALSE),
('Emilia Romagna Grand Prix',	'2022.04.24',	(select id from f1_location where f1_location."name" ='Autodromo Enzo e Dino Ferrari'), FALSE),
('Miami Grand Prix',	'2022.05.08',	(select id from f1_location where f1_location."name" =	'Miami International Autodrome'), FALSE),
('Spanish Grand Prix',	'2022.05.22',	(select id from f1_location where f1_location."name" =	'Circuit de Barcelona-Catalunya'), FALSE),
('Monaco Grand Prix',	'2022.05.29',	(select id from f1_location where f1_location."name" =	'Circuit de Monaco'), FALSE),
('Azerbaijan Grand Prix',	'2022.06.12',	(select id from f1_location where f1_location."name" =	'Baku City Circuit'), FALSE),
('Canadian Grand Prix',	'2022.06.19',	(select id from f1_location where f1_location."name" =	'Circuit Gilles Villeneuve'), FALSE),
('British Grand Prix',	'2022.07.03',	(select id from f1_location where f1_location."name" =	'Silverstone Circuit'), FALSE),
('Austrian Grand Prix',	'2022.07.10',	(select id from f1_location where f1_location."name" =		'Red Bull Ring'), FALSE),
('French Grand Prix',	'2022.07.24',	(select id from f1_location where f1_location."name" =	'Circuit Paul Ricard'), FALSE),
('Hungarian Grand Prix',	'2022.07.31',	(select id from f1_location where f1_location."name" =	'Hungaroring'), FALSE),
('Belgian Grand Prix',	'2022.08.28',	(select id from f1_location where f1_location."name" =	'Circuit de Spa-Francorchamps'), FALSE),
('Dutch Grand Prix',	'2022.09.04',	(select id from f1_location where f1_location."name" =	'Circuit Park Zandvoort'), FALSE),
('Italian Grand Prix',	'2022.09.11',	(select id from f1_location where f1_location."name" =	'Autodromo Nazionale di Monza'), FALSE),
('Singapore Grand Prix',	'2022.10.02',	(select id from f1_location where f1_location."name" =	'Marina Bay Street Circuit'), FALSE),
('Japanese Grand Prix',	'2022.10.09',	(select id from f1_location where f1_location."name" =	'Suzuka Circuit'), FALSE),
('United States Grand Prix',	'2022.10.23',	(select id from f1_location where f1_location."name" =	'Circuit of the Americas'), FALSE),
('Mexico City Grand Prix',	'2022.10.30',	(select id from f1_location where f1_location."name" =	'Autódromo Hermanos Rodríguez'), FALSE),
('Brazilian Grand Prix',	'2022.11.13',	(select id from f1_location where f1_location."name" =	'Autódromo José Carlos Pace'), FALSE),
('Abu Dhabi Grand Prix',	'2022.11.20',	(select id from f1_location where f1_location."name" =	'Yas Marina Circuit'), FALSE);