# Generated by Django 3.2.9 on 2022-04-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0003_auto_20220406_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=140)),
                ('country', models.CharField(max_length=140)),
            ],
        ),
        migrations.AlterField(
            model_name='race',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='f1.location'),
        ),
    ]
