# Generated by Django 3.2.9 on 2022-04-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0004_auto_20220409_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
    ]
