# Generated by Django 3.2.9 on 2022-04-09 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('f1', '0005_remove_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='fia_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fia_officers', to=settings.AUTH_USER_MODEL),
        ),
    ]
