# Generated by Django 3.2.9 on 2022-04-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0006_complaint_fia_officer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointsupdate',
            old_name='reace',
            new_name='race',
        ),
    ]
